/* Generated by Yosys 0.54 (git sha1 db72ec3bde296a9512b2d1e6fabf81cfb07c2c1b, clang++ 19.1.7 -fPIC -O3) */

module F_isNaN(a, isNaN, isInf, isNegInf, isSubnormal, isZero, isNormal);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  input [31:0] a;
  wire [31:0] a;
  output isInf;
  wire isInf;
  output isNaN;
  wire isNaN;
  output isNegInf;
  wire isNegInf;
  output isNormal;
  wire isNormal;
  output isSubnormal;
  wire isSubnormal;
  output isZero;
  wire isZero;
  sg13g2_nor4_1 _16_ (
    .A(a[5]),
    .B(a[4]),
    .C(a[7]),
    .D(a[6]),
    .Y(_00_)
  );
  sg13g2_nor4_1 _17_ (
    .A(a[1]),
    .B(a[0]),
    .C(a[3]),
    .D(a[2]),
    .Y(_01_)
  );
  sg13g2_nand2_1 _18_ (
    .A(_00_),
    .B(_01_),
    .Y(_02_)
  );
  sg13g2_nor4_1 _19_ (
    .A(a[9]),
    .B(a[8]),
    .C(a[11]),
    .D(a[10]),
    .Y(_03_)
  );
  sg13g2_nor4_1 _20_ (
    .A(a[13]),
    .B(a[12]),
    .C(a[15]),
    .D(a[14]),
    .Y(_04_)
  );
  sg13g2_nand2_1 _21_ (
    .A(_03_),
    .B(_04_),
    .Y(_05_)
  );
  sg13g2_nor2_1 _22_ (
    .A(a[17]),
    .B(a[16]),
    .Y(_06_)
  );
  sg13g2_nor4_1 _23_ (
    .A(a[19]),
    .B(a[18]),
    .C(a[21]),
    .D(a[20]),
    .Y(_07_)
  );
  sg13g2_nand2_1 _24_ (
    .A(_06_),
    .B(_07_),
    .Y(_08_)
  );
  sg13g2_nand4_1 _25_ (
    .A(a[28]),
    .B(a[27]),
    .C(a[30]),
    .D(a[29]),
    .Y(_09_)
  );
  sg13g2_nand4_1 _26_ (
    .A(a[24]),
    .B(a[23]),
    .C(a[26]),
    .D(a[25]),
    .Y(_10_)
  );
  sg13g2_nor2_1 _27_ (
    .A(_09_),
    .B(_10_),
    .Y(_11_)
  );
  sg13g2_nand2_1 _28_ (
    .A(a[22]),
    .B(_11_),
    .Y(_12_)
  );
  sg13g2_nor4_1 _29_ (
    .A(_02_),
    .B(_05_),
    .C(_08_),
    .D(_12_),
    .Y(isNaN)
  );
  sg13g2_nor4_1 _30_ (
    .A(a[22]),
    .B(_02_),
    .C(_05_),
    .D(_08_),
    .Y(_13_)
  );
  sg13g2_and2_1 _31_ (
    .A(_11_),
    .B(_13_),
    .X(isInf)
  );
  sg13g2_nor4_1 _32_ (
    .A(a[28]),
    .B(a[27]),
    .C(a[30]),
    .D(a[29]),
    .Y(_14_)
  );
  sg13g2_nor4_1 _33_ (
    .A(a[24]),
    .B(a[23]),
    .C(a[26]),
    .D(a[25]),
    .Y(_15_)
  );
  sg13g2_and2_1 _34_ (
    .A(_14_),
    .B(_15_),
    .X(isNormal)
  );
  sg13g2_nor2b_1 _35_ (
    .A(_13_),
    .B_N(isNormal),
    .Y(isSubnormal)
  );
  sg13g2_tielo _36_ (
    .L_LO(isNegInf)
  );
  sg13g2_buf_1 _37_ (
    .A(isInf),
    .X(isZero)
  );
endmodule
