/* Generated by Yosys 0.54 (git sha1 db72ec3bde296a9512b2d1e6fabf81cfb07c2c1b, clang++ 19.1.7 -fPIC -O3) */

module F_isNaN(a, isNaN, isInf, isNegInf, isSubnormal, isZero, isNormal);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  input [31:0] a;
  wire [31:0] a;
  output isInf;
  wire isInf;
  output isNaN;
  wire isNaN;
  output isNegInf;
  wire isNegInf;
  output isNormal;
  wire isNormal;
  output isSubnormal;
  wire isSubnormal;
  output isZero;
  wire isZero;
  sg13g2_inv_1 _20_ (
    .A(a[23]),
    .Y(_00_)
  );
  sg13g2_nor4_1 _21_ (
    .A(a[5]),
    .B(a[4]),
    .C(a[7]),
    .D(a[6]),
    .Y(_01_)
  );
  sg13g2_nor4_1 _22_ (
    .A(a[1]),
    .B(a[0]),
    .C(a[3]),
    .D(a[2]),
    .Y(_02_)
  );
  sg13g2_nand2_1 _23_ (
    .A(_01_),
    .B(_02_),
    .Y(_03_)
  );
  sg13g2_nor4_1 _24_ (
    .A(a[9]),
    .B(a[8]),
    .C(a[11]),
    .D(a[10]),
    .Y(_04_)
  );
  sg13g2_nor4_1 _25_ (
    .A(a[13]),
    .B(a[12]),
    .C(a[15]),
    .D(a[14]),
    .Y(_05_)
  );
  sg13g2_nand2_1 _26_ (
    .A(_04_),
    .B(_05_),
    .Y(_06_)
  );
  sg13g2_and4_1 _27_ (
    .A(a[27]),
    .B(a[26]),
    .C(a[29]),
    .D(a[28]),
    .X(_07_)
  );
  sg13g2_nand3_1 _28_ (
    .A(a[25]),
    .B(a[24]),
    .C(_07_),
    .Y(_08_)
  );
  sg13g2_nand2b_1 _29_ (
    .A_N(a[31]),
    .B(a[30]),
    .Y(_09_)
  );
  sg13g2_nor2_1 _30_ (
    .A(a[17]),
    .B(a[16]),
    .Y(_10_)
  );
  sg13g2_nor4_1 _31_ (
    .A(a[19]),
    .B(a[18]),
    .C(a[21]),
    .D(a[20]),
    .Y(_11_)
  );
  sg13g2_nand2_1 _32_ (
    .A(_10_),
    .B(_11_),
    .Y(_12_)
  );
  sg13g2_nand2_1 _33_ (
    .A(a[23]),
    .B(a[22]),
    .Y(_13_)
  );
  sg13g2_or4_1 _34_ (
    .A(_08_),
    .B(_09_),
    .C(_12_),
    .D(_13_),
    .X(_14_)
  );
  sg13g2_nor3_1 _35_ (
    .A(_03_),
    .B(_06_),
    .C(_14_),
    .Y(isNaN)
  );
  sg13g2_or4_1 _36_ (
    .A(a[22]),
    .B(_03_),
    .C(_06_),
    .D(_12_),
    .X(_15_)
  );
  sg13g2_nor4_1 _37_ (
    .A(_00_),
    .B(_08_),
    .C(_09_),
    .D(_15_),
    .Y(isInf)
  );
  sg13g2_nand3_1 _38_ (
    .A(a[23]),
    .B(a[31]),
    .C(a[30]),
    .Y(_16_)
  );
  sg13g2_nor3_1 _39_ (
    .A(_08_),
    .B(_15_),
    .C(_16_),
    .Y(isNegInf)
  );
  sg13g2_nor4_1 _40_ (
    .A(a[26]),
    .B(a[29]),
    .C(a[28]),
    .D(a[30]),
    .Y(_17_)
  );
  sg13g2_nor4_1 _41_ (
    .A(a[23]),
    .B(a[25]),
    .C(a[24]),
    .D(a[27]),
    .Y(_18_)
  );
  sg13g2_nand2_1 _42_ (
    .A(_17_),
    .B(_18_),
    .Y(_19_)
  );
  sg13g2_inv_1 _43_ (
    .A(_19_),
    .Y(isNormal)
  );
  sg13g2_nor2_1 _44_ (
    .A(_15_),
    .B(_19_),
    .Y(isZero)
  );
  sg13g2_and2_1 _45_ (
    .A(_15_),
    .B(isNormal),
    .X(isSubnormal)
  );
endmodule
